### ISSUE TITLE
AFter importing all posts have the same id

### ISSUE THREAD

**Issue by hollowr** [BenWard/tumblr2wordpress#15]
After importing when i go to edit articles all the articles have the same edit ID so i can't edit and change date s or else.

is there a solution to that? have tried to empty all the tables and so on, but no luck. does wordpress save a file to remember as it is always the same id that comes up.

thanks for a great tool. that had worked for me before.

**Comment by hollowr** [comment]
just to clarify the post id in the table is not the same but the edit ID in the edit.php page are all the same.

**Comment by BenWard** [comment]
Oh. Blast. Apparently the fix I snuck in regarding the WordPress ID issue previously (which was just to remove the WordPress ID) didn't work the way I expected it to. I'll try to reproduce this myself, and then figure out the best bet. If WP is using the WP ID as canonical, there's going to be a problem since avoiding collisions with existing entries is a must.

**Comment by BenWard** [comment]
This seems to work fine on WordPress.com. Are you importing into a self hosted version? Can I just check you're running the latest version of WordPress 3 and so on and so forth? I'll have to set up a dev environment for that separately.

**Comment by hollowr** [comment]
self hosted, wordpress 3.05 to be exact and the latest importer.

**Comment by BenWard** [comment]
OK. I'll have a go at reproducing that in the next few days.

**Comment by hollowr** [comment]
Nice!
Before your last update. I had problems importing as it failed. import said "HAVE FUN" but nothing was imported. This time it imports everything ok except for that ID problem.

To be more precise i reinstalled the latest wordpress and imported as is, no themes no extensions. And of courses not reusing the tables.

**Comment by hollowr** [comment]
As an update i went through the database and found that the import where fine until a certain number and then all the most recent posts got the same identifier on the edit page. Hope that can help.

Thanks
