### ISSUE TITLE
Error fetching Tumblr posts

### ISSUE THREAD

**Issue by mrm362** [BenWard/tumblr2wordpress#3]
Receiving error:

"Error fetching Tumblr posts
String could not be parsed as XML
950 posts fetched"

I successfully transferred a Tumblr blog over to Wordpress with about 6000 posts 2 weeks ago, but now I receive the error above. 

The tumblr blog I've been trying to transfer is http://maryrambin.tumblr.com/

**Comment by BenWard** [comment]
Closing as duplicate.

**Comment by BenWard** [comment]
Status on this, and comments: http://github.com/BenWard/tumblr2wordpress/issues/issue/5
