### ISSUE TITLE
Error fetching Tumblr posts 

### ISSUE THREAD

**Issue by jakelevine** [BenWard/tumblr2wordpress#5]
Hi Ben,

Thanks for this script but unfortunately it does not seem to be working for me. Can you advise? My blog is at jakelevine.tumblr.com

Best,
Jake

My error:
Error fetching Tumblr posts
String could not be parsed as XML  200 posts fetched

**Comment by BenWard** [comment]
There's definitely some flakey behaviour with collecting all the posts from Tumblr. I'm rewriting that piece of code at the moment, and there should be something new to try shortly (say, an hour from now.)

**Comment by BenWard** [comment]
Merge from other issue: http://maryrambin.tumblr.com/  fails as well.

**Comment by BenWard** [comment]
Switching to using curl for Tumblr API requests has greater improved the stability of the script; I can't reproduce the failure on `jakelevine` anymore.

In the event of network/API failure, the script will now output much more detailed debugging information. It's not very smart or refined, but if Tumblr throws up, you'll at least be able to see what the error is an act accordingly. Oftentimes, if the API goes down or is overloaded, the solution will just be to retry the export after a few minutes. The script could certainly do smarter things there (pausing, retrying, doing a partial export), but for the time being I don't see that level of user-friendliness as a priority. So long as people know what the failure was, and so long as it works reliable most of the time, I think that is sufficient for our purposes.

Code is updated and tagged as v0.3.1.
